name: Deploy

# Deploy to dev on push to main
# Deploy to dev and prod when a release tag is created
on:
  push:
    branches:
      - main
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+
  release:
    types:
      - published
  # - created
  # - released

# Set run-name to the release tag if event is a release, otherwise use the default run-name
run-name: ${{ github.event_name == 'release' && format('Release - {0}', github.event.release.tag_name) || '' }}

env:
  GO_VERSION: 1.19.3
  TERRAFORM_VERSION: 1.3.5
  ENVIRONMENT: dev # Used when populating the terraform variable: "environment"
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  # Use release tag during  set TAG to the release tag, otherwise use the sha
  TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || github.sha }}

jobs:
  get_image_tag:
    name: Get image tag
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_image_tag.outputs.image_tag }}
    steps:
      - name: Get image tag
        id: get_image_tag
        run: |
          echo "Image tag: ${{ env.TAG }}"

  deploy_dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: get_image_tag
    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploy to Dev"
          echo "Image tag: ${{ env.TAG }}"

  # Only run if event is a release
  deploy_prod:
    if: ${{ github.event_name == 'release' }}
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: [deploy_dev, get_image_tag]
    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploy to Prod"
          echo "Image tag: ${{ env.TAG }}"
