name: Release

# Deploy to dev on push to main
# Deploy to dev and prod when a release tag is created
on:
  push:
    # branches:
    #   - main
    # paths-ignore:
    #   # - "CHANGELOG.md"
    #   - "README.md"
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+
  release:
    types:
      - published
      # - created
      # - released
env:
  GO_VERSION: 1.19.3
  TERRAFORM_VERSION: 1.3.5
  ENVIRONMENT: dev # Used when populating the terraform variable: "environment"

jobs:
  deploy_dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploy to Dev"

  # Only run if tag is pushed
  deploy_prod:
    # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: deploy_dev
    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploy to Prod"
